/**
 * Comprehensive list of chess opening names as they appear in Lichess game data.
 * Format: "Family: Variation" — used for search-autocomplete in the opening filter.
 * The filter uses substring matching, so searching "Najdorf" will match
 * "Sicilian Defense: Najdorf Variation" etc.
 */
export const ALL_OPENINGS: string[] = [
    // ── Sicilian Defense ──────────────────────────────────────────────────────
    'Sicilian Defense',
    'Sicilian Defense: Najdorf Variation',
    'Sicilian Defense: Najdorf Variation, English Attack',
    'Sicilian Defense: Najdorf Variation, Amsterdam Variation',
    'Sicilian Defense: Najdorf Variation, Poisoned Pawn Variation',
    'Sicilian Defense: Dragon Variation',
    'Sicilian Defense: Dragon Variation, Yugoslav Attack',
    'Sicilian Defense: Dragon Variation, Classical Variation',
    'Sicilian Defense: Dragon Variation, Levenfish Variation',
    'Sicilian Defense: Accelerated Dragon',
    'Sicilian Defense: Scheveningen Variation',
    'Sicilian Defense: Scheveningen Variation, English Attack',
    'Sicilian Defense: Kan Variation',
    'Sicilian Defense: Taimanov Variation',
    'Sicilian Defense: Four Knights Variation',
    'Sicilian Defense: Alapin Variation',
    'Sicilian Defense: Grand Prix Attack',
    'Sicilian Defense: Closed Variation',
    'Sicilian Defense: Classical Variation',
    'Sicilian Defense: Richter-Rauzer Attack',
    'Sicilian Defense: Sozin Attack',
    'Sicilian Defense: Velimirovic Attack',
    'Sicilian Defense: O\'Kelly Variation',
    'Sicilian Defense: Löwenthal Variation',
    'Sicilian Defense: Smith-Morra Gambit',
    'Sicilian Defense: Wing Gambit',
    'Sicilian Defense: Hyper-Accelerated Dragon',
    'Sicilian Defense: Chekhover Variation',
    'Sicilian Defense: Pin Variation',
    'Sicilian Defense: Nimzowitsch Variation',
    'Sicilian Defense: Pelikan Variation',
    'Sicilian Defense: Sveshnikov Variation',
    // ── Ruy Lopez ─────────────────────────────────────────────────────────────
    'Ruy Lopez',
    'Ruy Lopez: Berlin Defense',
    'Ruy Lopez: Berlin Defense, Rio Gambit Accepted',
    'Ruy Lopez: Morphy Defense',
    'Ruy Lopez: Morphy Defense, Breyer Defense',
    'Ruy Lopez: Morphy Defense, Chigorin Defense',
    'Ruy Lopez: Morphy Defense, Zaitsev Variation',
    'Ruy Lopez: Marshall Attack',
    'Ruy Lopez: Open Defense',
    'Ruy Lopez: Closed Defense',
    'Ruy Lopez: Exchange Variation',
    'Ruy Lopez: Steinitz Defense',
    'Ruy Lopez: Classical Defense',
    'Ruy Lopez: Bird\'s Defense',
    'Ruy Lopez: Schliemann Defense',
    'Ruy Lopez: Cozio Defense',
    'Ruy Lopez: Arkhangelsk Variation',
    'Ruy Lopez: Anti-Marshall',
    // ── French Defense ────────────────────────────────────────────────────────
    'French Defense',
    'French Defense: Winawer Variation',
    'French Defense: Classical Variation',
    'French Defense: Tarrasch Variation',
    'French Defense: Rubinstein Variation',
    'French Defense: Advance Variation',
    'French Defense: Exchange Variation',
    'French Defense: King\'s Indian Attack',
    'French Defense: Steinitz Variation',
    'French Defense: MacCutcheon Variation',
    'French Defense: Burn Variation',
    'French Defense: Normal Variation',
    // ── Italian Game ──────────────────────────────────────────────────────────
    'Italian Game',
    'Italian Game: Giuoco Piano',
    'Italian Game: Classical Variation',
    'Italian Game: Quiet Game',
    'Italian Game: Two Knights Defense',
    'Italian Game: Evans Gambit',
    'Italian Game: Hungarian Defense',
    'Italian Game: Fried Liver Attack',
    'Italian Game: Scotch Gambit',
    // ── Caro-Kann Defense ─────────────────────────────────────────────────────
    'Caro-Kann Defense',
    'Caro-Kann Defense: Classical Variation',
    'Caro-Kann Defense: Advance Variation',
    'Caro-Kann Defense: Exchange Variation',
    'Caro-Kann Defense: Panov Attack',
    'Caro-Kann Defense: Karpov Variation',
    'Caro-Kann Defense: Tartakower Variation',
    'Caro-Kann Defense: Bronstein-Larsen Variation',
    'Caro-Kann Defense: Two Knights Attack',
    'Caro-Kann Defense: Maróczy Variation',
    'Caro-Kann Defense: Fantasy Variation',
    'Caro-Kann Defense: Gurgenidze System',
    // ── Queen\'s Gambit ────────────────────────────────────────────────────────
    'Queen\'s Gambit Accepted',
    'Queen\'s Gambit Accepted: Classical Defense',
    'Queen\'s Gambit Accepted: Normal Variation',
    'Queen\'s Gambit Declined',
    'Queen\'s Gambit Declined: Orthodox Defense',
    'Queen\'s Gambit Declined: Tartakower Defense',
    'Queen\'s Gambit Declined: Ragozin Defense',
    'Queen\'s Gambit Declined: Semi-Tarrasch Defense',
    'Queen\'s Gambit Declined: Exchange Variation',
    'Queen\'s Gambit Declined: Manhattan Variation',
    'Queen\'s Gambit Declined: Cambridge Springs Defense',
    'Queen\'s Gambit Declined: Vienna Variation',
    'Slav Defense',
    'Slav Defense: Modern Line',
    'Slav Defense: Exchange Variation',
    'Slav Defense: Three Knights Variation',
    'Slav Defense: Czech Variation',
    'Slav Defense: Winawer Countergambit',
    'Semi-Slav Defense',
    'Semi-Slav Defense: Meran Variation',
    'Semi-Slav Defense: Anti-Meran Variation',
    'Semi-Slav Defense: Botvinnik System',
    'Semi-Slav Defense: Accelerated Move Order',
    // ── King\'s Indian Defense ────────────────────────────────────────────────
    'King\'s Indian Defense',
    'King\'s Indian Defense: Classical Variation',
    'King\'s Indian Defense: Four Pawns Attack',
    'King\'s Indian Defense: Sämisch Variation',
    'King\'s Indian Defense: Averbakh Variation',
    'King\'s Indian Defense: Fianchetto Variation',
    'King\'s Indian Defense: Orthodox Variation',
    'King\'s Indian Defense: Makogonov Variation',
    'King\'s Indian Defense: Normal Variation',
    'King\'s Indian Defense: Petrosian Variation',
    'King\'s Indian Defense: Mar del Plata Variation',
    // ── Nimzo-Indian Defense ─────────────────────────────────────────────────
    'Nimzo-Indian Defense',
    'Nimzo-Indian Defense: Classical Variation',
    'Nimzo-Indian Defense: Rubinstein Variation',
    'Nimzo-Indian Defense: Sämisch Variation',
    'Nimzo-Indian Defense: Three Knights Variation',
    'Nimzo-Indian Defense: Reshevsky Variation',
    'Nimzo-Indian Defense: Normal Variation',
    'Nimzo-Indian Defense: Fischer Variation',
    'Nimzo-Indian Defense: Leningrad Variation',
    'Nimzo-Indian Defense: Hübner Variation',
    // ── English Opening ──────────────────────────────────────────────────────
    'English Opening',
    'English Opening: Symmetrical Variation',
    'English Opening: King\'s English Variation',
    'English Opening: Anglo-Indian Defense',
    'English Opening: Mikenas-Carls Variation',
    'English Opening: Four Knights System',
    'English Opening: Agincourt Defense',
    'English Opening: Reversed Sicilian',
    // ── Catalan Opening ──────────────────────────────────────────────────────
    'Catalan Opening',
    'Catalan Opening: Open Defense',
    'Catalan Opening: Closed Variation',
    // ── Grünfeld Defense ─────────────────────────────────────────────────────
    'Grünfeld Defense',
    'Grünfeld Defense: Exchange Variation',
    'Grünfeld Defense: Three Knights Variation',
    'Grünfeld Defense: Russian Variation',
    'Grünfeld Defense: Stockholm Variation',
    // ── Dutch Defense ────────────────────────────────────────────────────────
    'Dutch Defense',
    'Dutch Defense: Leningrad Variation',
    'Dutch Defense: Classical Variation',
    'Dutch Defense: Stonewall Variation',
    'Dutch Defense: Anti-Dutch Variation',
    // ── Other 1.d4 openings ───────────────────────────────────────────────────
    'London System',
    'Queen\'s Indian Defense',
    'Queen\'s Indian Defense: Classical Variation',
    'Queen\'s Indian Defense: Petrosian Variation',
    'Queen\'s Indian Defense: Kasparov Variation',
    'Benoni Defense',
    'Benoni Defense: Modern Variation',
    'Benoni Defense: Classical Variation',
    'Benko Gambit',
    'Budapest Gambit',
    'Trompowsky Attack',
    'Torre Attack',
    // ── Scotch Game ──────────────────────────────────────────────────────────
    'Scotch Game',
    'Scotch Game: Classical Variation',
    'Scotch Game: Göring Gambit',
    'Scotch Game: Mieses Variation',
    'Scotch Game: Schmidt Variation',
    // ── Other 1.e4 openings ──────────────────────────────────────────────────
    'Scandinavian Defense',
    'Scandinavian Defense: Modern Variation',
    'Scandinavian Defense: Mieses-Kotroc Variation',
    'King\'s Gambit',
    'King\'s Gambit Accepted',
    'King\'s Gambit Declined',
    'Vienna Game',
    'Vienna Game: Vienna Gambit',
    'Four Knights Game',
    'Four Knights Game: Spanish Variation',
    'Four Knights Game: Italian Variation',
    'Two Knights Defense',
    'Petrov\'s Defense',
    'Petrov\'s Defense: Classical Attack',
    'Philidor Defense',
    'Alekhine\'s Defense',
    'Alekhine\'s Defense: Modern Variation',
    'Pirc Defense',
    'Pirc Defense: Classical Variation',
    'Pirc Defense: Austrian Attack',
    'Pirc Defense: Byrne Variation',
    'Modern Defense',
    'Modern Defense: Averbakh System',
    // ── Flank openings ───────────────────────────────────────────────────────
    'Réti Opening',
    'Réti Opening: King\'s Indian Attack',
    'King\'s Indian Attack',
    'Bird\'s Opening',
    'Bird\'s Opening: Dutch Variation',
    'Nimzo-Larsen Attack',
    'Nimzowitsch Defense',
];
